### PR TITLE
Add YouTube link

### PR DESCRIPTION
**Pull request by MGomezN**
**Description**

**Relevant issues/PRs**

### CODE REVIEW

**Comment by MGomezN** [comment]
Disclaimer. This is a superficial comment. Not suitable for people busy with serious matters.

I had a happy morning editing the recording videos of the Development call today, 
feeling the power of  the phrase: " Leonardo Uieda invited you to manage Fatiando a Terra"✊🏽, 
then uploading the video... 
then realizing the upload was in my account 🤣, 
then deleting my mistake,
then uploading again, this time in the right place... 
then having a fantasy about creating a Youtube "Maintainance playlist" 
then realizing that a playlist without a proper thumbnail is not a playlist is like a life without love... or worst...  
then asking myself where to find the materials to create one image like the one in the Community calls, 
then aligning my mind with the Fatiando Mind -a very high level of conscience that allows you to find the things where they suppose to be https://github.com/fatiando/logo/tree/main/social
then realizing I have no idea how to use SVG
then realizing the clue was right there in the repository: Inkscape
then playing with Inkscape trying to find the proper Font for my magical "Maintenance" title,
then asking desperately for help to [WhatTheFont! - MyFonts](https://www.myfonts.com/WhatTheFont/)
then realized I didn't have $89 to buy [Droid Serif Pro WGL Bold](https://www.myfonts.com/fonts/ascender/droid-serif-pro/bold/)
then choosing a similar Font 🤔 
then generating the Youtube link and including this here https://github.com/fatiando/community/blob/main/development-calls/2022.md and here https://hackmd.io/@fatiando/development-calls-2022... discovering I have to edit each file independently,
then starting a party/action movie/thriller in #49 by creating and killing stuff :hurtrealbad: because I forgot to add a space between lines in the MD file...
then making this pull request to humble ask for the addition of the Youtube link 😃

**Comment by leouieda** [comment]
😆 Love the narrative, as always @MGomezN!

For the record, we usually edit only the HackMD file. We have HackMD connected to this repo so we can tell it to push any changes from there onto here. This should probably be made clearer somewhere (the README here maybe?)

To avoid causing conflicts for HackMD, I'll close this PR and will push your changes from there instead.

**Comment by leouieda** [comment]
>  aligning my mind with the Fatiando Mind -a very high level of conscience that allows you to find the things where they suppose to be

🤣  our motto is "there is a repo for that somewhere"

**Comment by leouieda** [comment]
Added in https://github.com/fatiando/community/commit/1cd9c388bbd352a295f1adce701215b06739a713

**Pull request closed without merging**
