### PR TITLE
Create a checklist for onboarding new maintainers

### PR DESCRIPTION
**Pull request by leouieda**
Add this as a new section to the MAINTENANCE guide.

### CODE REVIEW

**Comment by aguspesce** [comment]
They are baby steps! super sweet

**Comment by leouieda** [comment]
❤️

**Comment by santisoler** [comment]
Nice! Are we planning some steps for adding them as maintainers of the conda-forge feedstock repos?

**Comment by leouieda** [comment]
@santisoler  good catch! Let's add that to this checklist

**Pull request merged**
